### ISSUE TITLE
Segmentation fault when training on Ubuntu 16.04

### ISSUE THREAD

**Issue by clw5180** [fizyr/keras-retinanet#860]
I tried to train my own dataset on Ubuntu16.04. After the word 'Epoch 1/50' , I got error 'segmentation fault'. Here is the imformation before the segmentation fault came up:
```
Using TensorFlow backend.
C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:65:00.0
totalMemory: 8.00GiB freeMemory: 6.53GiB
2019-01-03 00:15:52.705641: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2019-01-03 00:15:53.438635: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-03 00:15:53.441423: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0
2019-01-03 00:15:53.443366: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N
2019-01-03 00:15:53.445381: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6278 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:65:00.0, compute capability: 7.5)
Creating model, this may take a second...

Layer (type)                    Output Shape         Param #     Connected to
input_1 (InputLayer)            (None, None, None, 3 0
....................

Total params: 36,382,957
Trainable params: 36,276,717
Non-trainable params: 106,240
__________________________________________________________________________________________________
None
Epoch 1/50
```

I don't know what cause the  'segmentation fault', and how to deal with it ? Hope someone can help me , thanks a lot !!   ：）

**Comment by martinzlocha** [comment]
@clw5180 Given that you created #862 it seems that this is now resolved. What was the cause for this and can this issue be closed?

**Comment by de-vri-es** [comment]
Also, these seem deceptively Windowsy paths for Ubuntu...

**Comment by clw5180** [comment]
> Also, these seem deceptively Windowsy paths for Ubuntu...

I just being a little lazy, not put up the error message in Ubuntu...They are basically the same. It's my fault: )

**Comment by clw5180** [comment]
> resolved

The problem still not be solved, however I can run the code on Windows so it doesn't matter. I'll close this issue.

**Comment by clw5180** [comment]
> @clw5180 Given that you created #862 it seems that this is now resolved. What was the cause for this and can this issue be closed?

The problem still not be solved, however I can run the code on Windows so it doesn't matter. I'll close this issue.
