### ISSUE TITLE
Keras_resnet 'module' object has no attribute 'custom_objects'

### ISSUE THREAD

**Issue by hoangminhtoan** [fizyr/keras-retinanet#92]
When I run keras-retinanet it raises a follow error

  File ~/keras-retinanet/keras_retinanet/models/resnet.py", line 25, in <module>
    custom_objects.update(keras_resnet.custom_objects)
AttributeError: 'module' object has no attribute 'custom_objects'

I also tried to run on both python 2 and 3 but still got the same error

**Comment by panda9095** [comment]
You installed the wrong $keras-resnet$.
Follow the installation section of REAME should fix it.

**Comment by hgaiser** [comment]
@hoangminhtoan did this fix your issue?

**Comment by hoangminhtoan** [comment]
Thanks I can run the project. I install keras_renet by using pip instead of installing keras_renet from master branch as construction.

**Comment by de-vri-es** [comment]
Good to hear! Closing the issue as it seems resolved.

**Comment by taewookim** [comment]
I'm still getting this error even with keras-resnet installed.

FYI: 

$ pip install keras-resnet
Requirement already satisfied: keras-resnet in c:\anaconda3\lib\site-packages\keras_resnet-0.0.8-py3.6.egg
Requirement already satisfied: keras in c:\anaconda3\lib\site-packages (from keras-resnet)
Requirement already satisfied: pyyaml in c:\anaconda3\lib\site-packages (from keras->keras-resnet)
Requirement already satisfied: scipy>=0.14 in c:\anaconda3\lib\site-packages (from keras->keras-resnet)
Requirement already satisfied: six>=1.9.0 in c:\anaconda3\lib\site-packages (from keras->keras-resnet)
Requirement already satisfied: numpy>=1.9.1 in c:\anaconda3\lib\site-packages (from keras->keras-resnet)

**Comment by hgaiser** [comment]
Seems you need to read the README again.

**Comment by taewookim** [comment]
Oops. My apologies. I ran pip install keras-resnet instead of pip install --user --upgrade git+https://github.com/broadinstitute/keras-resnet

Thank you @hgaiser

**Comment by RobAngel** [comment]
I did read the ReadME and executed

pip install --user --upgrade git+https://github.com/broadinstitute/keras-resnet

and pip freeze shows:

Keras==2.1.3
keras-resnet==0.0.8
keras-retinanet==0.0.1

When I attempt to train on my on CSV files, I get the following:

Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/ra/.virtualenvs/keras-retinanet/bin/retinanet-train", line 11, in <module>
    load_entry_point('keras-retinanet==0.0.1', 'console_scripts', 'retinanet-train')()
  File "/Users/ra/.virtualenvs/keras-retinanet/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/ra/.virtualenvs/keras-retinanet/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/Users/ra/.virtualenvs/keras-retinanet/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/Users/ra/.virtualenvs/keras-retinanet/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ra/.virtualenvs/keras-retinanet/lib/python2.7/site-packages/keras_retinanet-0.0.1-py2.7.egg/keras_retinanet/bin/train.py", line 41, in <module>
    from ..models.resnet import resnet50_retinanet, custom_objects
  File "/Users/ra/.virtualenvs/keras-retinanet/lib/python2.7/site-packages/keras_retinanet-0.0.1-py2.7.egg/keras_retinanet/models/resnet.py", line 28, in <module>
    custom_objects.update(keras_resnet.custom_objects)
AttributeError: 'module' object has no attribute 'custom_objects'

Any ideas on why I'm still getting this AttributeError?

**Comment by hgaiser** [comment]
Are you by any chance running with python2.7 and installing with pip in python3 ? Can you check if your version in `keras_resnet/__init__.py` looks the same as [this one](https://github.com/broadinstitute/keras-resnet/blob/master/keras_resnet/__init__.py)?

**Comment by RobAngel** [comment]
Yes, it is identical..

from . import layers

custom_objects = {
    'BatchNormalization': layers.BatchNormalization,
}

**Comment by RobAngel** [comment]
Ok, I realized I didn't have the permissions on my Python folder set properly.  Once I corrected that was able to get past this error.  Sorry for the trouble.  I'm sure I'll be back with other questions in another thread.  Thanks for this repository.

**Comment by snarb** [comment]
I have the same error on windows. Fresh install today. Have tried both standard  pip install  and pip install --user --upgrade git+https://github.com/broadinstitute/keras-resnet. The same error on the line from keras_retinanet.models.resnet import custom_objects.  @RobAngel what permission are you talking about write permissions?

**Comment by hoangminhtoan** [comment]
@snarb. Sorry cannot help you because I use ubuntu not a windows

**Comment by msollami** [comment]
I'm seeing this issue as well.

**Comment by Tixierae** [comment]
I'm experiencing the same issue on Ubuntu after a fresh install and running `pip install --user --upgrade git+https://github.com/broadinstitute/keras-resnet`. Will keep trying.

**Comment by hgaiser** [comment]
Try running pip install --user --upgrade keras-retinanet

**Comment by Tixierae** [comment]
thx for the quick reply. Unfortunately, this doesn't solve my issue. I'm on Python 3 btw.

**Comment by Tixierae** [comment]
This is good advice, thanks. I will go with a virtual env and let you know about the outcome.
